POST http://localhost:3000/todos
Content-Type: application/json

{
    "title": "Take Shower"
}

###

GET http://localhost:3000/todos

###

GET http://localhost:3000/todos/1

###

PATCH http://localhost:3000/todos/1
Content-Type: application/json

{
    "status": true
}

###

DELETE http://localhost:3000/todos/1

###

POST http://localhost:3000/auth/register
Content-Type: application/json

{
    "name": "test",
    "email": "test3@test.com",
    "mobile": "+9779818000002",
    "password": "test"
}

###

POST http://localhost:3000/auth/login
Content-Type: application/json

{
    "username": "test3@test.com",
    "password": "test"
}
